language: go

go:
- master

install:
- go get github.com/stretchr/testify/assert
- go get github.com/mattn/goveralls

sudo: false

script:
- go test -v -covermode=count -coverprofile=coverage.out
- $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci